use_frameworks!

target 'WSLog_Example' do
  pod 'WSLog', :path => '../'

  target 'WSLog_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
